# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26ea9de022808ebc6aab1f7c789bc1b034ff6a086c992c1d92c8975c81212e342dbe8a4d23e1dda8c35104bd6e469fa1c1c698242b0bb887131a5c3f17e274f2

test:
  secret_key_base: 072225d03e6db4c20f21a97e5e786f5b3105de215d5341f988ddde8a7562778d36d1d812b33dda7e5437299c809b1f29e299310fe68ec07d0068f76e9d986f3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
